name: Bug report
description: Something isn't working correctly with the theme
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behavior in the [existing issues](https://github.com/chipzoller/hugo-clarity/issues).

        If you have a question, please use [GitHub Discussions](https://github.com/chipzoller/hugo-clarity/discussions) rather than posting an issue.

        ---

        Thank you for taking the time to file a bug report! To address this bug as fast as possible, we need some information.
  - type: checkboxes
    id: confirm_prereqs
    attributes:
      label: "I confirm:"
      options:
        - label: "I am running the [extended version of Hugo version 0.91.0 or above](https://github.com/chipzoller/hugo-clarity/blob/master/README.md#prerequisites) installed."
          required: true
        - label: "I have read the [theme documentation](https://github.com/chipzoller/hugo-clarity/blob/master/README.md)."
          required: true
        - label: "I have used the [example site's config files](https://github.com/chipzoller/hugo-clarity/tree/master/exampleSite/config/_default) as reference."
          required: true
        - label: "I have searched other issues in this repository and mine is not recorded."
          required: true
  - type: input
    id: v_hugo
    attributes:
      label: Hugo version
      description: 'Run `hugo version` and paste the output here.'
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: For example, iOS 14, Windows 10, macOS 12.5, Linux Ubuntu 22.04, Android 12, etc.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: For example, Chrome 76, Safari 13, etc.
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: 
        Describe how the bug shows up. You can also provide a link to a repo
        or a live website, or include screenshots.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe what you expect the behavior to be without the bug.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Explain the steps required to duplicate the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description:
        If applicable, provide any errors, stacktraces or other output from Hugo.
      render: shell
  - type: textarea
    id: related_code
    attributes:
      label: Related code
      description:
        If you have already identified the file or lines in the existing code
        that may be relevant to this bug, providing them will help speed up
        our response.
  - type: textarea
    id: solution
    attributes:
      label: Preferred solution
      description:
        If you have a suggested technical solution to this bug, please describe
        it here.
  - type: textarea
    id: other_info
    attributes:
      label: Other information
      description: Any other information that might be relevant to this bug.
  - type: markdown
    attributes:
      value: |
        ---

        **Thank you!**
