blank_issues_enabled: false
contact_links:
  - name: Read Hugo Clarity documentation
    url: https://github.com/chipzoller/hugo-clarity/blob/master/README.md
    about:
      If you're new to Hugo Clarity, check our docs for configuration details and 
      other information.
  - name: Theme contribution guide
    url: https://github.com/chipzoller/hugo-clarity/blob/master/CONTRIBUTING.md
    about: Help us make this theme great!